### ISSUE TITLE
Version 2.8.2 breaks IE11

### ISSUE THREAD

**Issue by indiggojorge** [highcharts/highcharts-angular#239]
I get a blank screen with an unhelpful console log when I use version 2.8.2 of highcharts-angular. I do not have this problem with version 2.8.0.

To reproduce, go to any page using highcharts using IE11.

I am using ...
 - NodeJS v12.16.1
 - Angular version 9.1.11
 - TypeScript version 3.8.3

**Comment by mateuszkornecki** [comment]
@indiggojorge Thanks for reporting the issue! 

We will investigate the problem and post a reply when we will find anything.

**Comment by mateuszkornecki** [comment]
Are you sure that everything was working correctly with the 2.8.0 version? The 2.8.2 update was a minor one - we changed just a required dependencies version so it shouldn't affect wrapper compatibility. 

To use angular 8/9+ in the IE you need to use a polyfill, could you tell me if you included it? 

**Similar ticket**: https://github.com/highcharts/highcharts-angular/issues/31
**References:** https://indepth.dev/angular-internet-explorer#summary--11/

**Comment by MoroccanGeek** [comment]
@mateuszkornecki I have the same issue with 2.8.2. 

I'm using Angular 9.1.11 too + highchart@8.2.2, and when I install the highcharts-angular@2.8.0 it works perfectly, but with 2.8.2 it gives me the following error when compiling : 

`Compiling highcharts-angular : module as esm5
Warning: Invalid constructor parameter decorator in D:/Projects/Project/demoApp/node_modules/highcharts-angular/fesm2015/highcharts-angular.js:
 () => [
    { type: ElementRef },
    { type: NgZone }
]
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected HighchartsChartComponent to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
    at Object.extractDirectiveMetadata (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:237:69)
    at ComponentDecoratorHandler.analyze (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:143:47)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step (D:\Projects\Project\demoApp\node_modules\tslib\tslib.js:140:27)
    at Object.next (D:\Projects\Project\demoApp\node_modules\tslib\tslib.js:121:57)
    at D:\Projects\Project\demoApp\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (D:\Projects\Project\demoApp\node_modules\tslib\tslib.js:110:16)
    at EventEmitter.<anonymous> (D:\Projects\Project\demoApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:314:20)
An unhandled exception occurred: NGCC failed.
`

**Comment by mateuszkornecki** [comment]
@MoroccanGeek Thanks for reporting the issue. 

Have you tried to solve it by including the polyfill mentioned in my previous answer?

**Comment by indiggojorge** [comment]
We are now running version 2.10.X of highcharts-angular. We no longer have an IE11 issue. We've made other changes as well and don't know which one resolved our problem. Thanks for looking into it.

**Comment by mateuszkornecki** [comment]
I am glad that you solved the problem!
