### ISSUE TITLE
Trying to use highcharts gives error on compiling getInternalNameOfClass() called on a non-ES5 class

### ISSUE THREAD

**Issue by Jerome2606** [highcharts/highcharts-angular#261]
Hi,

I just installed highcharts and highcharts-angular versions : 
8.2.2
2.9.0

and I'm facing this error after 'ng serve':
```
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected HighchartsChartComponent to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
    at Object.extractDirectiveMetadata (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:237:69)
    at ComponentDecoratorHandler.analyze (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:143:47)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step (C:\Projects\Backoffice\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\Projects\Backoffice\node_modules\tslib\tslib.js:120:57)
    at C:\Projects\Backoffice\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Projects\Backoffice\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (C:\Projects\Backoffice\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:310:20)
An unhandled exception occurred: NGCC failed.
```

I tried from my ts.config to switch between es5 and es2015 target but nothing working.
The compiler refuses to work with this package.

I'm using angular version 9.1.12

Thanks,

Jerome

**Comment by mateuszkornecki** [comment]
@Jerome2606 Thanks for reporting the issue!

I was trying to reproduce the problem on my own (using the exact highcharts, highcharts-angular, and angular version) and it was working correctly on my own. Could you reproduce the problem in a simple angular problem that you might give me access to, so I can check what is not working or what could be done?

**Comment by Jerome2606** [comment]
Maybe it can be link to my tsconfig :
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "target": "es5"
  },
  "types": [
    "leaflet"
  ]
}
```

and tsconfig.app.json
```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/app",
    "target": "es5",
    "module": "es2015",
    "baseUrl": "",
    "types": [
      "lodash",
      "jquery"
    ]
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

Here'is my angular.json as well:

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "portal": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/android-chrome-192x192.png",
              "src/android-chrome-256x256.png",
              "src/apple-touch-icon.png",
              "src/apple-touch-icon-60x60.png",
              "src/apple-touch-icon-60x60-precomposed.png",
              "src/apple-touch-icon-76x76.png",
              "src/apple-touch-icon-76x76-precomposed.png",
              "src/apple-touch-icon-120x120.png",
              "src/apple-touch-icon-120x120-precomposed.png",
              "src/apple-touch-icon-152x152.png",
              "src/apple-touch-icon-152x152-precomposed.png",
              "src/apple-touch-icon-180x180.png",
              "src/apple-touch-icon-180x180-precomposed.png",
              "src/apple-touch-icon-precomposed-precomposed.png",
              "src/browserconfig.xml",
              "src/favicon.ico",
              "src/favicon-16x16.png",
              "src/favicon-32x32.png",
              "src/manifest.json",
              "src/mstile-144x144.png",
              "src/mstile-150x150.png",
              "src/safari-pinned-tab.svg",
              "src/web.config",
              "src/silent.html"
            ],
            "styles": [
              "src/styles.scss",
              "vendor/fontawesome-pro/css/all.css",
              "node_modules/famfamfam-flags/dist/sprite/famfamfam-flags.min.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/ngx-bootstrap/datepicker/bs-datepicker.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/bootstrap-sass/assets/javascripts/bootstrap.js",
              "node_modules/moment/min/moment.min.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "portal:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "portal:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "portal:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/bootstrap-sass/assets/javascripts/bootstrap.js",
              "node_modules/moment/min/moment.min.js"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "assets": [
              "src/assets",
              "src/android-chrome-192x192.png",
              "src/android-chrome-256x256.png",
              "src/apple-touch-icon.png",
              "src/apple-touch-icon-60x60.png",
              "src/apple-touch-icon-60x60-precomposed.png",
              "src/apple-touch-icon-76x76.png",
              "src/apple-touch-icon-76x76-precomposed.png",
              "src/apple-touch-icon-120x120.png",
              "src/apple-touch-icon-120x120-precomposed.png",
              "src/apple-touch-icon-152x152.png",
              "src/apple-touch-icon-152x152-precomposed.png",
              "src/apple-touch-icon-180x180.png",
              "src/apple-touch-icon-180x180-precomposed.png",
              "src/apple-touch-icon-precomposed-precomposed.png",
              "src/browserconfig.xml",
              "src/favicon.ico",
              "src/favicon-16x16.png",
              "src/favicon-32x32.png",
              "src/manifest.json",
              "src/mstile-144x144.png",
              "src/mstile-150x150.png",
              "src/safari-pinned-tab.svg",
              "src/web.config",
              "src/silent.html"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": []
          }
        }
      }
    },
    "portal-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "portal:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": []
          }
        }
      }
    }
  },
  "defaultProject": "portal",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "bloub",
      "styleExt": "scss"
    },
    "defaults": {
      "styleExt": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "bloub"
    }
  },
  "cli": {
    "analytics": false
  }
}

```

and my cli Version:

```

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 12.16.2
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/http                     7.2.16
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.2
typescript                        3.8.3
webpack                           4.42.0
```

Can you share your project with the same versions ?
Maybe I can make a comparison with mine and check what's is the root of the issue.

Jérôme

**Comment by Jerome2606** [comment]
This kind of error seems to come from ivy compilation:
https://github.com/SoCreate/angular-playground/issues/235

when you are doing ng --version, do you have "Ivy Workspace: Yes" on your side as well ?

**Comment by mateuszkornecki** [comment]
> Can you share your project with the same versions ?
> Maybe I can make a comparison with mine and check what's is the root of the issue.
>
> Jérôme

Sure here you are, `angular 9.1.12`, `highcharts 8.2.2`, `highcharts-angular 2.9.0`:
https://github.com/mateuszkornecki/ng-912



> This kind of error seems to come from ivy compilation:
> [SoCreate/angular-playground#235](https://github.com/SoCreate/angular-playground/issues/235)
> 
> when you are doing ng --version, do you have "Ivy Workspace: Yes" on your side as well ?

Yes, that's right.

**Comment by niravIntentlabs** [comment]
@Jerome2606 I had a same problem. Tried to create a different project with `angular 9.1.12, highcharts 8.2.2, highcharts-angular 2.9.0:` and it was working properly, but in other project I am stilling getting the same error. 

I have added “postinstall”:”ngcc” inside "script" json in package.json file. After adding it, it's working properly.

**Comment by DoanVanThuong** [comment]
Same Issue with me

**Comment by karolkolodziej** [comment]
Closing due to inactivity.
