### ISSUE TITLE
2.10.0: Cannot read properties of null (reading 'responsive')

### ISSUE THREAD

**Issue by mbausche** [highcharts/highcharts-angular#323]
we have the followig code

```
this.options=createOptions(...) // never returns null
this.chartInstance.update(this.options, true, true);

```
which causes (in rare cases) the following error:

```
core.js:4117 ERROR TypeError: Cannot read properties of null (reading 'responsive')
    at a.setResponsive (highcharts.js:581:439)
    at a.update (highcharts.js:394:444)
    at HighchartsChartComponent.updateOrCreateChart (highcharts-angular.js:34:1)
    at HighchartsChartComponent.wrappedUpdateOrCreateChart (highcharts-angular.js:29:1)
    at HighchartsChartComponent.ngOnChanges (highcharts-angular.js:16:1)
    at HighchartsChartComponent.wrapOnChangesHook_inPreviousChangesStorage (core.js:19464:1)
```
This happens while accessing chart.options which seemes to be null...

BUT: We have no code where we do a  `this.chartInstance.options = null`

**Comment by karolkolodziej** [comment]
Are you able to reproduce that in some online code editor so that I can see a bigger picture?
Because for now, I don't fully understand the issue.
