### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'chart') (highcharts-more.js:198:422)

### ISSUE THREAD

**Issue by fensefernando** [highcharts/highcharts-angular#328]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
I create a spider chart with example. https://codesandbox.io/s/671rn2vn3?file=/package.json. But, I when mouse over chart. On console write this error

core.mjs:6362 ERROR TypeError: Cannot read properties of undefined (reading 'chart')
    at b.searchPointByAngle [as searchPoint] (highcharts-more.js:198:422)
    at highcharts.js:307:208
    at Array.forEach (<anonymous>)
    at f.findNearestKDPoint (highcharts.js:307:109)
    at f.getHoverData (highcharts.js:310:162)
    at f.runPointActions (highcharts.js:323:344)
    at f.onContainerMouseMove (highcharts.js:316:124)
    at HTMLDivElement.wrapFn (zone.js:766:39)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26316:33)

### Expected behavior
Don't show error

### Demo
Please provide live demo of the problem or provide any other way to recreate the problem.

#### Steps required to recreate the problem in the demo:
1. ...

### Setup used
 - NodeJS version  v16.14.0
 - Angular version v14
 - TypeScript version 4.7.2
etc.

**Comment by karolkolodziej** [comment]
I'm sorry but I'm not able to recreate that by simply hovering over the chart.
Could you please elaborate on what should I do in order to get this error?

**Comment by karolkolodziej** [comment]
Closing due to inactivity.
