### ISSUE TITLE
Packed Bubble Chart error

### ISSUE THREAD

**Issue by boskiv** [highcharts/highcharts-angular#363]
```
sentry-angular-ivy.js:154 Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=packedbubble
 - missingModuleFor: packedbubble
    at Object.<anonymous> (highcharts.js:12:223)
    at d (highcharts.js:18:24)
    at x (highcharts.js:12:146)
    at ea.initSeries (highcharts.js:409:257)
    at highcharts.js:438:223
    at Array.forEach (<anonymous>)
    at ea.firstRender (highcharts.js:438:201)
    at ea.<anonymous> (highcharts.js:409:169)
    at d (highcharts.js:18:24)
    at ea.init (highcharts.js:408:64)
```

```
Highcharts: typeof Highcharts = Highcharts;
  chartOptions: Highcharts.Options = {
    series:[
      {
        type: 'packedbubble',
        name: 'A',
        data: [{
          name: 'B',
          value: 6,
        }, {
          name: 'C',
          value: 2,
        }]
      }
    ]
```
```
<highcharts-chart
    [Highcharts]="Highcharts"
    [options]="chartOptions"

    style="width: 100%; height: 400px; display: block;"
  ></highcharts-chart>
  ```

**Comment by boskiv** [comment]
Fixed with
```
import * as Highcharts from 'highcharts';
import darkUnica from 'highcharts/themes/dark-unica';
import HighchartsMore from 'highcharts/highcharts-more';
HighchartsMore(Highcharts);
darkUnica(Highcharts);
```
